namespace Assets {
    export const textures: Dict<Preload.Texture> = {
        'blank': {},

        // Debug
        'debug': {},

        // Level
        'arena1_walls': {},
        'centerblades': { anchor: Vector2.CENTER },
        'arena_bday_walls': {},
        'arena_bday_bg': {},
        'arena_bday_deco': {},
        'arena_space': { url: 'arena_space.lci' },
        'arena_ice': { url: 'arena_ice.lci' },
        'arena_gravity': { url: 'arena_gravity.lci' },
        'trampoline': {
            anchor: Vector2.TOP_CENTER,
            spritesheet: { frameWidth: 160, frameHeight: 87 },
        },
        'arena_factory': { url: 'arena_factory.lci' },
        'factorypipe': { anchor: Vector2.TOP_CENTER },

        // FX
        'aura': { anchor: Vector2.CENTER },
        'buffsigns': {
            anchor: Vector2.CENTER,
            frames: {
                'buff+': { rect: rect(0, 0, 7, 7) },
                'buff-': { rect: rect(7, 0, 7, 7) },
            }
        },
        'buffbeams': { anchor: Vector2.CENTER },
        'necromancerbeams': { anchor: Vector2.CENTER },
        'spike': { anchor: Vector2.CENTER },
        'sap': { anchor: Vector2.CENTER },
        'clawslash': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 28, frameHeight: 28 },
        },
        'buffcat': { anchor: Vector2.CENTER },
        'psychiceye': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 20, frameHeight: 14 },
        },
        'medkit': { anchor: Vector2.CENTER },
        'medkitdmg': { anchor: Vector2.CENTER },
        'voodoo': { anchor: Vector2.CENTER },
        'vampring': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 56, frameHeight: 56 },
        },
        'cue': { anchor: Vector2.CENTER_LEFT },
        'reduce': { anchor: Vector2.CENTER },
        'boomerbullet': { anchor: Vector2.CENTER },
        'nullified': { anchor: Vector2.CENTER },
        'landmine': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 10, frameHeight: 10 },
        },
        'scrapbullet': { anchor: Vector2.CENTER },
        'ghost': { anchor: Vector2.CENTER },
        'crosshair': { anchor: Vector2.CENTER },
        'speedflame': { anchor: Vector2.CENTER },

        // Balls
        'balls': {
            anchor: vec2(0.5, 0.25),
            frames: {
                'balls/8ball': { rect: rect(0, 0, 16, 32) },
                'balls/assassin': { rect: rect(16, 0, 16, 32) },
                'balls/ballofice': { rect: rect(32, 0, 16, 32) },
                'balls/ballofyarn': { rect: rect(48, 0, 16, 32) },
                'balls/biogrenade': { rect: rect(64, 0, 8, 16) },
                'balls/booster': { rect: rect(80, 0, 16, 32) },
                'balls/buffer': { rect: rect(96, 0, 16, 32) },
                'balls/coin': { rect: rect(112, 0, 16, 32) },
                'balls/commando': { rect: rect(0, 32, 16, 32) },
                'balls/crown': { rect: rect(16, 32, 16, 32) },
                'balls/crusher': { rect: rect(32, 32, 16, 32) },
                'balls/crystalball': { rect: rect(48, 32, 16, 32) },
                'balls/cueball': { rect: rect(64, 32, 16, 32) },
                'balls/deathstar': { rect: rect(80, 32, 32, 64) },
                'balls/gacha': { rect: rect(112, 32, 16, 32) },
                'balls/gladiator': { rect: rect(0, 64, 16, 32) },
                'balls/greencrystalball': { rect: rect(16, 64, 16, 32) },
                'balls/grenade': { rect: rect(32, 64, 16, 32) },
                'balls/healer': { rect: rect(48, 64, 16, 32) },
                'balls/leech': { rect: rect(64, 64, 16, 32) },
                'balls/martyr': { rect: rect(112, 64, 16, 32) },
                'balls/mechanic': { rect: rect(0, 96, 16, 32) },
                'balls/medic': { rect: rect(16, 96, 16, 32) },
                'balls/mercenary': { rect: rect(32, 96, 16, 32) },
                'balls/necromancer': { rect: rect(48, 96, 16, 32) },
                'balls/ninja': { rect: rect(64, 96, 16, 32) },
                'balls/normal': { rect: rect(80, 96, 16, 32) },
                'balls/pickleball': { rect: rect(96, 96, 16, 32) },
                'balls/pokeball': { rect: rect(112, 96, 16, 32) },
                'balls/powerball': { rect: rect(0, 128, 16, 32) },
                'balls/psychic': { rect: rect(16, 128, 16, 32) },
                'balls/recycler': { rect: rect(32, 128, 16, 32) },
                'balls/redcrystalball': { rect: rect(48, 128, 16, 32) },
                'balls/sapper': { rect: rect(64, 128, 16, 32) },
                'balls/skeleton': { rect: rect(80, 128, 16, 32) },
                'balls/sniper': { rect: rect(96, 128, 16, 32) },
                'balls/snowball': { rect: rect(112, 128, 16, 32) },
                'balls/spiker': { rect: rect(0, 160, 16, 32) },
                'balls/splinter': { rect: rect(16, 160, 16, 32) },
                'balls/split': { rect: rect(32, 160, 16, 32) },
                'balls/splitspawn': { rect: rect(48, 160, 8, 16) },
                'balls/thief': { rect: rect(64, 160, 16, 32) },
                'balls/trainer': { rect: rect(80, 160, 16, 32) },
                'balls/turret': { rect: rect(96, 160, 16, 32) },
                'balls/vagrant': { rect: rect(112, 160, 16, 32) },
                'balls/vampire': { rect: rect(0, 192, 16, 32) },
                'balls/vanguard': { rect: rect(16, 192, 16, 32) },
                'balls/voodooball': { rect: rect(32, 192, 16, 32) },
                'balls/wobby1': { rect: rect(48, 192, 16, 32) },
                'balls/wobby2': { rect: rect(64, 192, 16, 32) },
                'balls/wobby3': { rect: rect(80, 192, 16, 32) },
                'balls/wobby4': { rect: rect(96, 192, 16, 32) },
                'balls/zombie': { rect: rect(112, 192, 16, 32) },
                'balls/bank': { rect: rect(0, 224, 16, 32) },
                'balls/butterball': { rect: rect(16, 224, 16, 32) },
                'balls/reducer': { rect: rect(32, 224, 16, 32) },
                'balls/matryoshkaxl': { rect: rect(128, 0, 32, 64) },
                'balls/matryoshkal': { rect: rect(160, 0, 22, 44) },
                'balls/matryoshkam': { rect: rect(182, 0, 16, 32) },
                'balls/matryoshkas': { rect: rect(198, 0, 12, 24) },
                'balls/matryoshkaxs': { rect: rect(210, 0, 8, 16) },
                'balls/sleeper': { rect: rect(48, 224, 16, 32) },
                'balls/angel': { rect: rect(64, 224, 16, 32) },
                'balls/devil': { rect: rect(80, 224, 16, 32) },
                'balls/blackhole': { rect: rect(96, 224, 16, 32) },
                'balls/boomer': { rect: rect(112, 224, 16, 32) },
                'balls/zoomer': { rect: rect(224, 0, 16, 32) },
                'balls/guardian': { rect: rect(240, 0, 16, 32) },
                'balls/fragmenter': { rect: rect(192, 32, 16, 32) },
                'balls/watcher': { rect: rect(208, 32, 16, 32) },
                'balls/stinger': { rect: rect(224, 32, 16, 32) },
                'balls/wizard': { rect: rect(240, 32, 16, 32) },
                'balls/scavenger': { rect: rect(128, 64, 16, 32) },
                'balls/medkit': { rect: rect(144, 64, 16, 32) },
                'balls/cheel': { rect: rect(160, 64, 16, 32) },
                'balls/mimic': { rect: rect(176, 64, 16, 32) },
                'balls/fireball': { rect: rect(192, 64, 16, 32) },
                'balls/phoenix': { rect: rect(208, 64, 16, 32) },
                'balls/impostor': { rect: rect(224, 64, 16, 32) },
                'balls/miner': { rect: rect(240, 64, 16, 32) },
                'balls/hitman': { rect: rect(128, 96, 16, 32) },
                'balls/nullifier': { rect: rect(144, 96, 16, 32) },
                'balls/seed': { rect: rect(160, 96, 16, 32) },
                'balls/pinata': { rect: rect(176, 96, 16, 32) },
                'balls/questionball': { rect: rect(192, 96, 16, 32) },
                'balls/questionballspent': { rect: rect(208, 96, 16, 32) },
                'balls/dove': { rect: rect(224, 96, 16, 32) },
                'balls/watermelon': { rect: rect(240, 96, 16, 32) },
                'balls/grave': { rect: rect(128, 128, 16, 32) },
                'balls/scrapcannon': { rect: rect(144, 128, 16, 32) },
                'balls/haunt': { rect: rect(160, 128, 16, 32) },
                'balls/firefighter': { rect: rect(176, 128, 16, 32) },
                'balls/battery': { rect: rect(192, 128, 16, 32) },
                'balls/oldcrystalball': { rect: rect(208, 128, 16, 32) },
                'balls/neocrystalball': { rect: rect(224, 128, 16, 32) },
                'balls/dolly': { rect: rect(240, 128, 16, 32) },
                'balls/burner': { rect: rect(128, 160, 16, 32) },
                'balls/goldcrystalball': { rect: rect(144, 160, 16, 32) },
                'balls/alchemist': { rect: rect(160, 160, 16, 32) },
                'balls/seeker': { rect: rect(176, 160, 16, 32) },
                'balls/greatermimic': { rect: rect(192, 160, 16, 32) },
                'balls/toxin': { rect: rect(208, 160, 16, 32) },
                'balls/bowlingball': { rect: rect(224, 160, 16, 32) },
                'balls/stopper': { rect: rect(240, 160, 16, 32) },
                'balls/cannon': { rect: rect(128, 192, 22, 44) },
                'balls/cannonball': { rect: rect(160, 192, 16, 32) },
            }
        },

        'grenadehandle': { anchor: Vector2.CENTER },
        'turretgunbase': { anchor: Vector2.CENTER },
        'turretgunbarrel': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 22, frameHeight: 6 },
        },
        'biogrenadehandle': { anchor: Vector2.CENTER },
        'ballofyarntail': { anchor: Vector2.CENTER },
        'angelhalo': { anchor: Vector2.CENTER },
        'devilhorns': { anchor: Vector2.CENTER },
        'blackholecurl': { anchor: Vector2.CENTER },
        'blackholeoverlay': { anchor: Vector2.CENTER },
        'boomergun': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 20, frameHeight: 28 },
        },
        'wizardhat': { anchor: Vector2.CENTER },
        'stingerspike': { anchor: Vector2.CENTER },
        'phoenixashes': { anchor: Vector2.CENTER },
        'impostor_vent': {
            anchor: vec2(36/48, 13/32),
            spritesheet: { frameWidth: 48, frameHeight: 32 },
        },
        'scrapgunbase': { anchor: Vector2.CENTER },
        'scrapgunbarrel': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 8 },
        },
        'neocrystalballoverlay': { anchor: Vector2.CENTER },
        'cannongunbase': { anchor: Vector2.CENTER },
        'cannongunbarrel': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 40, frameHeight: 16 },
        },
        'mimictextures': {
            anchor: vec2(0.5, 0.25),
            frames: {
                'mimictextures/scrapcannon': { rect: rect(0, 0, 16, 32) },
                'mimictextures/turret': { rect: rect(16, 0, 16, 32) },
                'mimictextures/boomer': { rect: rect(32, 0, 16, 32) },
                'mimictextures/cannon': { rect: rect(48, 0, 22, 44) },
            }
        },

        // Ball Items
        'items': {
            anchor: Vector2.CENTER,
            frames: {
                'items/armorplating': { rect: rect(0, 0, 16, 16) },
                'items/bounty': { rect: rect(16, 0, 16, 16) },
                'items/rejuvenator': { rect: rect(32, 0, 16, 16) },
                'items/catears': { rect: rect(0, 16, 16, 16) },
                'items/magnet': { rect: rect(16, 16, 16, 16) },
                'items/guns': { rect: rect(32, 16, 16, 16) },
                'items/claws': { rect: rect(0, 32, 16, 16) },
                'items/polarityinverter': { rect: rect(16, 32, 16, 16) },
                'items/polarityinverterfan': { rect: rect(32, 32, 16, 16) },
                'items/clout': { rect: rect(0, 48, 16, 16) },
                'items/ballsharpener1': { rect: rect(16, 48, 16, 16) },
                'items/protectionbubble': { rect: rect(32, 48, 16, 16) },
                'items/hotpickle': { rect: rect(0, 64, 16, 16) },
                'items/pickle': { rect: rect(16, 64, 16, 16) },
                'items/starcatcher': { rect: rect(32, 64, 16, 16) },
                'items/polisher1': { rect: rect(0, 80, 16, 16) },
                'items/toxicfungus': { rect: rect(16, 80, 16, 16) },
                'items/redcube': { rect: rect(32, 80, 16, 16) },
                'items/shield': { rect: rect(0, 96, 16, 16) },
                'items/silencer': { rect: rect(16, 96, 16, 16) },
                'items/greencube': { rect: rect(32, 96, 16, 16) },
                'items/skullcharm': { rect: rect(0, 112, 16, 16) },
                'items/voodoopin': { rect: rect(16, 112, 16, 16) },
                'items/collectiblecoin': { rect: rect(32, 112, 16, 16) },
                'items/medkit': { rect: rect(0, 128, 16, 16) },
                'items/participationtrophy': { rect: rect(16, 128, 16, 16) },
                'items/cursedeye': { rect: rect(32, 128, 16, 16) },
                'items/timebomboff': { rect: rect(0, 144, 16, 16) },
                'items/timebomb': { rect: rect(16, 144, 16, 16) },
                'items/huntersmark': { rect: rect(32, 144, 16, 16) },
                'items/unstablecatalyst': { rect: rect(56, 0, 24, 24) },
                'items/scribbledmap': { rect: rect(80, 0, 24, 24) },
                'items/bestfriend': { rect: rect(104, 0, 24, 24) },
                'items/consolationprize': { rect: rect(56, 24, 24, 24) },
                'items/smokebomb': { rect: rect(80, 24, 24, 24) },
                'items/hyperdriver': { rect: rect(104, 24, 24, 24) },
                'items/orbitingpotato': { rect: rect(56, 48, 24, 24) },
                'items/spinach': { rect: rect(80, 48, 24, 24) },
                'items/overcharger': { rect: rect(104, 48, 24, 24) },
                'items/ballsharpener': { rect: rect(56, 72, 24, 24) },
                'items/supernova': { rect: rect(80, 72, 24, 24) },
                'items/polisher': { rect: rect(104, 72, 24, 24) },
                'items/bandaid': { rect: rect(56, 96, 24, 24) },
                'items/thiefmask': { rect: rect(80, 96, 24, 24) },
                'items/retroglasses': { rect: rect(104, 96, 24, 24) },
                'items/birthdaycake': { rect: rect(56, 120, 24, 24) },
                'items/mitosis': { rect: rect(80, 120, 24, 24) },
                'items/vipticket': { rect: rect(104, 120, 24, 24) },
                'items/mocha': { rect: rect(80, 144, 24, 24) },
                'items/thebug': { rect: rect(104, 144, 24, 24) },
                'items/gift': { rect: rect(128, 0, 24, 24) },
                'items/jetpack': { rect: rect(128, 24, 24, 24) },
                'items/contagion': { rect: rect(128, 48, 24, 24) },
                'items/moleculardisassembler': { rect: rect(128, 72, 24, 24) },
                'items/curseddoll': { rect: rect(128, 96, 24, 24) },
                'items/joker': { rect: rect(128, 120, 24, 24) },
                'items/curry': { rect: rect(128, 144, 24, 24) },
            }
        },

        // Equipments
        'equipments/orbiting': {
            anchor: Vector2.CENTER,
            frames: {
                'equipments/bestfriend': { rect: rect(0, 0, 12, 12) },
                'equipments/bandaid': { rect: rect(12, 0, 12, 12) },
                'equipments/bounty': { rect: rect(24, 0, 12, 12) },
                'equipments/claws': { rect: rect(36, 0, 12, 12) },
                'equipments/hyperdriver': { rect: rect(48, 0, 12, 12) },
                'equipments/magnet': { rect: rect(60, 0, 12, 12) },
                'equipments/rejuvenator': { rect: rect(72, 0, 12, 12) },
                'equipments/polarityinverter': { rect: rect(0, 12, 12, 12) },
                'equipments/polarityinverterfan': { rect: rect(12, 12, 12, 12) },
                'equipments/shield': { rect: rect(24, 12, 12, 12) },
                'equipments/silencer': { rect: rect(36, 12, 12, 12) },
                'equipments/skullcharm': { rect: rect(48, 12, 12, 12) },
                'equipments/smokebomb': { rect: rect(60, 12, 12, 12) },
                'equipments/toxicfungus': { rect: rect(72, 12, 12, 12) },
                'equipments/unstablecatalyst': { rect: rect(0, 24, 12, 12) },
                'equipments/vipticket': { rect: rect(12, 24, 12, 12) },
                'equipments/thiefmask': { rect: rect(24, 24, 12, 12) },
                'equipments/spore': { rect: rect(36, 24, 12, 12) },
                'equipments/medkit': { rect: rect(48, 24, 12, 12) },
                'equipments/mitosis': { rect: rect(60, 24, 12, 12) },
                'equipments/starcatcher': { rect: rect(72, 24, 12, 12) },
                'equipments/infection': { rect: rect(0, 36, 12, 12) },
                'equipments/redcube': { rect: rect(12, 36, 12, 12) },
                'equipments/greencube': { rect: rect(24, 36, 12, 12) },
                'equipments/curseddoll': { rect: rect(36, 36, 12, 12) },
                'equipments/cursedeye': { rect: rect(48, 36, 12, 12) },
                'equipments/joker': { rect: rect(60, 36, 12, 12) },
                'equipments/timebomb': { rect: rect(72, 36, 12, 12) },
                'equipments/huntersmark': { rect: rect(0, 48, 12, 12) },
                'equipments/curry': { rect: rect(12, 48, 12, 12) },
                'equipments/thebug': { rect: rect(24, 48, 12, 12) },
                'equipments/mocha': { rect: rect(36, 48, 12, 12) },
            }
        },
        'equipments/catears': { anchor: Vector2.CENTER },
        'equipments/gun': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 48, frameHeight: 48 },
        },
        'equipments/retroglasses': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 14, frameHeight: 8 },
        },
        'equipments/orbitingpotato': { anchor: Vector2.CENTER },
        'equipments/voodoopin': { anchor: Vector2.CENTER },
        'equipments/voodoopin_shoot': { anchor: Vector2.CENTER },
        'equipments/thief_hand': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 20, frameHeight: 14 },
        },
        'equipments/thruster': {
            anchor: vec2(2/12, 7/24),
            spritesheet: { frameWidth: 12, frameHeight: 24 },
        },
        'equipments/star_catcher': { anchor: vec2(14/20, 7/14) },

        // UI
        'dialogbox': { anchor: Vector2.CENTER },
        'dialogbox_name': { anchor: Vector2.CENTER },
        'slider': { anchor: Vector2.CENTER },
        'sliderbar': { anchor: Vector2.CENTER },
        'preppanel': { url: 'preppanel.lci' },
        'gear': { anchor: Vector2.CENTER },
        'gearsmall': { anchor: Vector2.CENTER },
        'infobox_9p': {},
        'dmgbox': { anchor: Vector2.CENTER },
        'hpbox': { anchor: Vector2.CENTER },
        'star': { anchor: Vector2.CENTER },
        'crown': { anchor: Vector2.CENTER },
        'pause': { anchor: Vector2.CENTER },
        'fastforward': { anchor: Vector2.CENTER },
        'countdown': {
            anchor: Vector2.CENTER,
            frames: {
                'countdown/3': { rect: rect(0, 0, 48, 80) },
                'countdown/2': { rect: rect(48, 0, 48, 80) },
                'countdown/1': { rect: rect(96, 0, 48, 80) },
                'countdown/0': { rect: rect(144, 0, 336, 80) },
            }
        },
        'achievementrewardbox': { anchor: Vector2.CENTER },
        'argpart1box': { anchor: Vector2.CENTER },
        'achievementscrollbar': {},
        'patchnotesscrollbar': {},
        'scrollbarhandle': {},
        'twitterlogosmall': { anchor: Vector2.CENTER },
        'imagelogosmall': { anchor: Vector2.CENTER },
        'freeze8': { anchor: Vector2.CENTER },
        'freeze16': { anchor: Vector2.CENTER },
        'vshearts': {},
        'vignette': {},
        'strategy': {},
        'checkmark': { anchor: Vector2.CENTER },
        'keyboardkey': { anchor: Vector2.CENTER },
        'keyboardkeybackspace': { anchor: Vector2.CENTER },
        'keyboardkeyshift': { anchor: Vector2.CENTER },
        'keyboardkeyspace': { anchor: Vector2.CENTER },
        'keyboardkeyenter': { anchor: Vector2.CENTER },
        'noballs': { anchor: Vector2.TOP },
        'bdayemojis': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 44, frameHeight: 44 },
        },
        'almanacentrybox': { anchor: Vector2.CENTER },
        'almanacscrollbar': {},
        'almanacmystery': { anchor: Vector2.CENTER },
        'lectvslogo': { anchor: Vector2.CENTER },
        'almanacicon': {
            anchor: Vector2.CENTER,
            frames: {
                'almanacicon/open': { rect: rect(0, 0, 24, 20) },
                'almanacicon/closed': { rect: rect(24, 0, 24, 20) },
            }
        },
        'dailyscrollbar': {},
        'dailyicons': {
            anchor: Vector2.CENTER,
            frames: {
                'dailyicons/pack/classic': { rect: rect(0, 0, 16, 16) },
                'dailyicons/pack/community': { rect: rect(16, 0, 16, 16) },
                'dailyicons/pack/all': { rect: rect(32, 0, 16, 16) },
                'dailyicons/pack/weekly': { rect: rect(48, 0, 16, 16) },

                'dailyicons/arena/first': { rect: rect(0, 16, 16, 16) },
                'dailyicons/arena/ice': { rect: rect(16, 16, 16, 16) },
                'dailyicons/arena/space': { rect: rect(32, 16, 16, 16) },
                'dailyicons/arena/factory': { rect: rect(48, 16, 16, 16) },
                'dailyicons/arena/gravity': { rect: rect(64, 16, 16, 16) },
                'dailyicons/arena/bday': { rect: rect(80, 16, 16, 16) },

                'dailyicons/modifier/nospeedcap': { rect: rect(0, 32, 16, 16) },
                'dailyicons/modifier/extradmg': { rect: rect(16, 32, 16, 16) },
                'dailyicons/modifier/extrahp': { rect: rect(32, 32, 16, 16) },
                'dailyicons/modifier/extrastars': { rect: rect(48, 32, 16, 16) },
                'dailyicons/modifier/lessgold': { rect: rect(64, 32, 16, 16) },
                'dailyicons/modifier/moregold': { rect: rect(80, 32, 16, 16) },
                'dailyicons/modifier/preequipped': { rect: rect(96, 32, 16, 16) },
                'dailyicons/modifier/sameballsstocked': { rect: rect(112, 32, 16, 16) },
                'dailyicons/modifier/birthday': { rect: rect(128, 32, 16, 16) },
                'dailyicons/modifier/unknown': { rect: rect(144, 32, 16, 16) },
                'dailyicons/modifier/packclash': { rect: rect(0, 48, 16, 16) },
                'dailyicons/modifier/sharedhp': { rect: rect(16, 48, 16, 16) },
                'dailyicons/modifier/spores': { rect: rect(32, 48, 16, 16) },
                'dailyicons/modifier/lesssell': { rect: rect(48, 48, 16, 16) },
                'dailyicons/modifier/moresell': { rect: rect(64, 48, 16, 16) },
                'dailyicons/modifier/challengemode': { rect: rect(80, 48, 16, 16) },
                'dailyicons/modifier/noitems': { rect: rect(96, 48, 16, 16) },
                'dailyicons/modifier/moreballs': { rect: rect(112, 48, 16, 16) },
                'dailyicons/modifier/slowcollisions': { rect: rect(128, 48, 16, 16) },
                'dailyicons/modifier/ballsexplode': { rect: rect(144, 48, 16, 16) },
                'dailyicons/modifier/earlyshrink': { rect: rect(0, 64, 16, 16) },
                'dailyicons/modifier/pickles': { rect: rect(16, 64, 16, 16) },
                'dailyicons/modifier/onlyintier': { rect: rect(32, 64, 16, 16) },
                'dailyicons/modifier/lesssquadsize': { rect: rect(48, 64, 16, 16) },
                'dailyicons/modifier/moresquadsize': { rect: rect(64, 64, 16, 16) },
                'dailyicons/modifier/lessrestockcost': { rect: rect(80, 64, 16, 16) },
                'dailyicons/modifier/morerestockcost': { rect: rect(96, 64, 16, 16) },
                'dailyicons/modifier/wallshurt': { rect: rect(112, 64, 16, 16) },
                'dailyicons/modifier/wallsbounce': { rect: rect(128, 64, 16, 16) },
            }
        },
        'infoicon': { anchor: Vector2.CENTER },

        // Achievements
        'achievements/playfivegames': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/wingame': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/strongball': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/roundsinarow': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/havetwentygold': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/reachroundtwelve': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 36, frameHeight: 36 },
        },
        'achievements/playhundredrounds': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/winfiftyrounds': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/victorywithtwoballs': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/makefivehundredpurchases': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/catearsonsquad': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/winintenminutes': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/strongsquad': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/winwithoutequipment': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/winwithoutfreezing': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/dealdamage': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/defeatcrownedsquads': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/midlevelball': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/healhp': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/ballgobrrr': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/sameball': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/sellcoin': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/windaily': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/dealburndamage': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/shootprojectiles': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/fiveremainingballs': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/completeballmanacentries': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/killbeforebattle': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/killenemiesinround': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/winweekly': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/argpart1': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/b': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/c': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/secret': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/peacewasneveranoption': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 72, frameHeight: 24 },
        },
        'achievements/birthday': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 20, frameHeight: 20 },
        },
        'achievements/getrevenge': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/defeatlectvs': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/defeatmaterwelons': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/defeatxephia': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/useless': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/completetheballmanac': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'achievements/numberone': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },
        'achievements/bugsquad': {
            anchor: Vector2.CENTER,
            spritesheet: { frameWidth: 32, frameHeight: 32 },
        },

        // Menu
        'mainmenu': { url: 'mainmenu.lci' },
        'playmenu': { url: 'playmenu.lci' },
        'packmenu': { url: 'packmenu.lci' },
        'vsmodemenu': { url: 'vsmodemenu.lci' },
        'vssettingsmenu': { url: 'vssettingsmenu.lci' },
        'optionsmenu': { url: 'optionsmenu.lci' },
        'cloudsavemenu': { url: 'cloudsavemenu.lci' },
        'credits/1': { url: 'credits/1.lci' },
        'credits/2': { url: 'credits/2.lci' },
        'credits/3': { url: 'credits/3.lci' },
        'achievementsmenu': { url: 'achievementsmenu.lci' },
        'patchnotesmenu': { url: 'patchnotesmenu.lci' },
        'almanacmenu': { url: 'almanacmenu.lci' },
        'dailymenu': { url: 'dailymenu.lci' },
        'dailyinfomenu': { url: 'dailyinfomenu.lci' },
        'tutorial1': { url: 'tutorial/1.lci' },
        'tutorial2': { url: 'tutorial/2.lci' },
        //'tutorial3': { url: 'tutorial/3.lci' },
        'bugged': { url: 'bugged.lci' },
        'trailer/title': { url: 'trailer/title.lci' },
        'trailer/build': { url: 'trailer/build.lci' },
        'trailer/battle': { url: 'trailer/battle.lci' },
        'trailer/playfree': { url: 'trailer/playfree.lci' },

        // ARG
        'arg/lobby': { url: 'arg/lobby.lci' },
        'arg/room1': { url: 'arg/room1.lci' },
        'arg/room2': { url: 'arg/room2.lci' },
        'arg/room3': { url: 'arg/room3.lci' },
        'arg/hall': { url: 'arg/hall.lci' },
        'arg/end': { url: 'arg/end.lci' },
        'arg/keypad': { url: 'arg/keypad.lci' },
        'arg/conference': { url: 'arg/conference.lci' },
        'arg/restricted': { url: 'arg/restricted.lci' },
        'arg/area1': { url: 'arg/area1.lci' },
        'arg/area2': { url: 'arg/area2.lci' },
        'arg/area3': { url: 'arg/area3.lci' },
        'arg/area4': { url: 'arg/area4.lci' },
        'arg/area5': { url: 'arg/area5.lci' },
        'arg/hallbeta': { url: 'arg/hallbeta.lci' },
        'arg/lab': { url: 'arg/lab.lci' },
        'arg/bec': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'arg/chester': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'arg/guardian': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 28, frameHeight: 44 },
        },
        'arg/wolf': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 24, frameHeight: 24 },
        },
        'arg/doctor': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 26, frameHeight: 38 },
        },
        'arg/scientist1': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 52, frameHeight: 54 },
        },
        'arg/scientist2': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 52, frameHeight: 54 },
        },
        'arg/scientist3': {
            anchor: Vector2.BOTTOM,
            spritesheet: { frameWidth: 44, frameHeight: 44 },
        },
        'arg/key': { anchor: Vector2.BOTTOM },
        'arg/box': { anchor: Vector2.BOTTOM },
        'arg/button': { anchor: Vector2.BOTTOM, spritesheet: { frameWidth: 12, frameHeight: 12 }},
        'arg/lasergen': { anchor: Vector2.BOTTOM, frames: {
            'arg/lasergen/up': { rect: rect(0, 0, 13, 19) },
            'arg/lasergen/down': { rect: rect(13, 0, 13, 19) },
        }},
        'arg/laserrec': { anchor: vec2(0.5, 17/20), frames: {
            'arg/laserrec/down/off': { rect: rect(0, 0, 13, 20) },
            'arg/laserrec/down/on': { rect: rect(13, 0, 13, 20) },
            'arg/laserrec/up/off': { rect: rect(26, 0, 13, 20) },
            'arg/laserrec/up/on': { rect: rect(39, 0, 13, 20) },
        }},
        'arg/gatev': { anchor: Vector2.BOTTOM, spritesheet: { frameWidth: 32, frameHeight: 20 }},
        'arg/gateh': { anchor: Vector2.BOTTOM, spritesheet: { frameWidth: 7, frameHeight: 46 }},
        'arg/autoballs': { anchor: Vector2.BOTTOM, spritesheet: { frameWidth: 20, frameHeight: 20 }},
        'arg/cabinet': { anchor: Vector2.CENTER, frames: {
            'arg/cabinet/closed': { rect: rect(0, 0, 32, 68) },
            'arg/cabinet/open': { rect: rect(32, 0, 32, 68) },
        }},
        'arg/qr_intro': { anchor: Vector2.CENTER },
        'arg/overlay': { url: 'arg/overlay.lci' },
        'arg/desktop': { url: 'arg/desktop.lci' },
        'arg/sabtitle': { url: 'arg/sabtitle.lci' },
        'arg/sabgame': { url: 'arg/sabgame.lci' },
        'arg/ball': { anchor: Vector2.CENTER, spritesheet: { frameWidth: 14, frameHeight: 14 }},
        'arg/ffgame': { url: 'arg/ffgame.lci' },
        'arg/hook': { anchor: vec2(0.5, 128/132) },
        'arg/softwareerror': { anchor: Vector2.CENTER },
        'arg/fish': { anchor: Vector2.CENTER },
        'arg/fishdead': { anchor: Vector2.CENTER },
        'arg/login': { url: 'arg/login.lci' },
        'arg/phiportrait': { anchor: Vector2.CENTER },
        'arg/sessionlocked': { anchor: Vector2.CENTER },
        'arg/kayportraits': {
            anchor: Vector2.CENTER,
            frames: {
                'arg/kayportraits/default': { rect: rect(0, 0, 80, 80) },
                'arg/kayportraits/smug': { rect: rect(80, 0, 80, 80) },
                'arg/kayportraits/cheek': { rect: rect(160, 0, 80, 80) },
                'arg/kayportraits/eyeroll': { rect: rect(240, 0, 80, 80) },
                'arg/kayportraits/nervous': { rect: rect(320, 0, 80, 80) },
                'arg/kayportraits/frown': { rect: rect(400, 0, 80, 80) },
                'arg/kayportraits/blank': { rect: rect(480, 0, 80, 80) },
                'arg/kayportraits/skeptical': { rect: rect(560, 0, 80, 80) },
                'arg/kayportraits/thinkingl': { rect: rect(640, 0, 80, 80) },
                'arg/kayportraits/thinkingr': { rect: rect(720, 0, 80, 80) },
            }
        },

        // Font
        'deluxe16_extras': { spritesheet: { frameWidth: 8, frameHeight: 15 } },
        'deluxe16_touch': { spritesheet: { frameWidth: 16, frameHeight: 18 } },
        'smallnumbers_extras': { spritesheet: { frameWidth: 4, frameHeight: 6 } },
    }

    export const sounds: Dict<Preload.Sound> = {
        // Debug
        'debug': {},

        // Menu
        'click': {},
        'menublip': {},
        'typename': {},
        'kay': {},
        'achievement': { volume: 1 },
        'wob': { url: 'blem.aac', volume: 1.5 },
        'yay': { volume: 1 },

        // General
        'shake': {},
        'shake2': { volume: 0.5 },
        'win': { volume: 0.5 },
        'lose': { volume: 0.5 },
        'draw': { volume: 0.5 },
        'countdown': {},
        'countdownfight': {},
        'pause': { volume: 0.7 },
        'unpause': { volume: 0.7 },
        'speedup': { volume: 1 },
        'impact': { volume: 1 },
        'sweep': { volume: 1 },
        'glitch': { volume: 1.5 },
        'pluckreverb': { volume: 1 },
        'ballcount': { volume: 1 },
        'ballcountreverb': { volume: 1 },
        'bookopen': { volume: 1 },
        'bookclose': { volume: 1 },

        // Shop
        'play': {},
        'sellball': {},
        'buyball': { volume: 0.6 },
        'pickupball': {},
        'putdownball': {},
        'error': {},
        'zapequip': { volume: 0.3 },
        'freeze': { volume: 1.5 },
        'unfreeze': { volume: 1 },
        'disintegrate': { volume: 0.7 },
        'charge': { volume: 0.3 },
        'windowserror': { volume: 1 },

        // Battle
        'ballhit': { volume: 0.2 },
        'hitwall': {},
        'balldie': { volume: 0.3 },
        'levelup': { volume: 0.5 },
        'implode': { volume: 0.5 },
        'buff': { volume: 0.3 },
        'shoot': { volume: 0.5 },
        'eqbreak': { volume: 0.7 },
        'spike': { volume: 0.4 },
        'steal': { volume: 1.3 },
        'zap': { volume: 0.5 },
        'cloak': { volume: 2 },
        'wub': { volume: 1, speed: 1 },
        'medkitout': {},
        'medkitheal': { volume: 0.5 },
        'medkitgrab': { volume: 0.5 },
        'diocharge': { volume: 0.7 },
        'dioboom': { volume: 0.7 },
        'cuehit': { volume: 1.5 },
        'reduce': { volume: 0.8 },
        'fireignite': { volume: 0.4 },
        'fire': { volume: 1.3 },
        'shaker': { volume: 0.7 },
        'beep': { volume: 0.5 },
        'beepbeep': { volume: 0.5 },
        'chain': { volume: 1.4 },
        'popper': { volume: 1 },
        'confetti': { volume: 1 },
        'trampoline': { volume: 1 },
        'dispenser': { volume: 2 },
        'rocket': { volume: 1 },
        'pew': { volume: 0.5 },
        'swoosh': { volume: 0.7 },
        'puff': { volume: 1 },
        'mariocoin': { volume: 0.25 },
        'splash': { volume: 0.6 },
        'scrap': { volume: 0.5 },
        'spook': { volume: 0.7 },
        'whisper': { volume: 1 },
        'stab': { volume: 0.7 },
        'slosh': { volume: 1.3 },
        'shootcannon': { volume: 0.7 },
        'stopboom': { volume: 0.7 },

        // ARG
        'arg/arg': {},
        'arg/walk': { volume: 0.7 },
        'arg/box_slide': { volume: 0.5 },
        'arg/pressureplate': { volume: 0.7 },
        'arg/laser': { volume: 0.5 },
        'arg/laser_start': { volume: 0.5 },
        'arg/securitydoor': {},
        'arg/lasergate': { volume: 0.5 },
        'arg/glitch_dialog': { volume: 0.8 },
        'arg/glitch_screen': { volume: 0.8 },
        'arg/reach': {},
        'arg/scene': {},
        'arg/bip': {},
        'arg/spark': {},
        'arg/tear': {},
        'arg/glitch_short': { volume: 0.8 },
        'arg/glitch_short_low': { volume: 0.8 },
        'arg/echo': { volume: 1 },
        'arg/pickup': { volume: 0.7 },
        'arg/unlock': { volume: 0.7 },
        'arg/riser': { volume: 0.5 },
        'arg/sight': { volume: 0.8 },
        'arg/glass': { volume: 1 },
        'arg/static': { volume: 1 },
        'arg/shot': { volume: 1.5 },
        'arg/softimpact': { volume: 2 },
        'arg/click': { volume: 1 },
        'arg/sabhurt': { volume: 0.7 },
        'arg/sabwall': { volume: 1 },
        'arg/sabpickup': { volume: 1.2 },
        'arg/sabputdown': { volume: 1.2 },
        'arg/sabselect': { volume: 1.2 },
        'arg/sabwin': { volume: 0.7 },
        'arg/sablose': { volume: 0.7 },
        'arg/sabintro1': { volume: 0.6 },
        'arg/sabintro2': { volume: 0.6 },
        'arg/sabintro3': { volume: 0.6 },
        'arg/sessionlocked': { volume: 1 },
        'arg/bubbles': {},
        'arg/tvstatic': { volume: 1 },

        // Dialog
        'dialogstart': { url: 'click.aac', volume: 0.5 },
        'dialogspeak': {},

        // Music
        'music/title': {},
        'music/shop': {},
        'music/shop2': { volume: 0.7 },
        'music/battle': {},
        'music/battle2': {},
        'arg/music_light': { volume: 0.7 },
        'arg/atmosphere': { volume: 0.7 },
        'arg/booms': { volume: 0.5 },
        'arg/computer': { volume: 1 },
        'arg/sabtitle': { volume: 0.6 },
        'arg/sabshop': { volume: 0.6 },
        'arg/sabbattle': { volume: 0.6 },
        'arg/ff': { url: 'arg/ff.wav', volume: 0.6 },
    }

    export const tilesets: Dict<Preload.Tileset> = {
    }

    export const pyxelTilemaps: Dict<Preload.PyxelTilemap> = {
    }

    export const fonts: Dict<Preload.Font> = {
        'deluxe16': {
            charWidth: 8,
            charHeight: 15,
            spaceWidth: 8,
            newlineHeight: 15,
            customCharacters: {
                'coin': 'deluxe16_extras/0',
                'heart': 'deluxe16_extras/1',
                'trophy': 'deluxe16_extras/2',
                'sword': 'deluxe16_extras/3',
                'lmb': 'deluxe16_extras/4',
                'rmb': 'deluxe16_extras/5',
                'star': 'deluxe16_extras/6',
                'etick': 'deluxe16_extras/7',
                'lte': 'deluxe16_extras/8',
                'clock': 'deluxe16_extras/9',
                'bullet': 'deluxe16_extras/10',
                'g1': 'deluxe16_extras/11',
                'g2': 'deluxe16_extras/12',
                'g3': 'deluxe16_extras/13',
                'g4': 'deluxe16_extras/14',
                'g5': 'deluxe16_extras/15',
                'crown': 'deluxe16_extras/16',
                'ntick': 'deluxe16_extras/17',
                'dove1': 'deluxe16_extras/18',
                'dove2': 'deluxe16_extras/19',

                'touch_hold': 'deluxe16_touch/0',
                'touch_drag': 'deluxe16_touch/1',
                'touch_tap': 'deluxe16_touch/2',
                'touch_hold_t': 'deluxe16_touch/3',
                'touch_drag_t': 'deluxe16_touch/4',
                'touch_tap_t': 'deluxe16_touch/5',
            }
        },
        'smallnumbers': {
            charWidth: 4,
            charHeight: 6,
            spaceWidth: 4,
            newlineHeight: 6,
            customCharacters: {
                'coin': 'smallnumbers_extras/0',
                'crownl': 'smallnumbers_extras/1',
                'crownr': 'smallnumbers_extras/2',
                'crown2l': 'smallnumbers_extras/3',
                'crown2r': 'smallnumbers_extras/4',
            }
        },
        'starnumbers': {
            charWidth: 8,
            charHeight: 8,
            spaceWidth: 8,
            newlineHeight: 8,
        },
    }

    export const customResources: Dict<Preload.CustomResource> = {
        'blurfilter': {
            load: () => BlurFilter.load(),
        },
        'arenafirstfilter': {
            load: () => ArenaFirstFilter.load(),
        },
        'contagionfilter': {
            load: () => Equipments.Contagion.loadFilter(),
        },
        'disintegratorfilter': {
            load: () => BallItems.MolecularDisassembler.loadFilter(),
        },
    }

    export const spriteTextTags: Dict<SpriteText.TagFunction> = {
        'dg': () => ({
            color: 0x007F0E,
        }),
        'pg': () => ({
            color: 0x00BB00,
        }),
        'gold': () => ({
            color: 0xFFD800,
        }),
        'dgold': () => ({
            color: 0xE0BB00,
        }),
        'purp': () => ({
            color: 0xB200FF,
        }),
        'dr': () => ({
            color: 0xAA0000,
        }),
        'rb': () => ({
            color: 0x0A27CC,
        }),
        'fb': () => ({
            color: 0x44FFFF,
        }),
        'pb': () => ({
            color: 0x22BBBB,
        }),
        'lb': () => ({
            color: 0x00FFFF,
        }),
        'w': () => ({
            color: 0xFFFFFF,
        }),
        'grey': () => ({
            color: 0x444444,
        }),
        'achx': () => ({
            offsetX: -1,
        }),
        'verx': () => ({
            offsetX: 2,
        }),
        'minorverx': () => ({
            offsetX: -1,
        }),
        'glitched': (params) => ({
            filters: [new Effects.Filters.Glitch(parseInt(params[0] ?? '2'), parseInt(params[1] ?? '4'), 2)],
        }),
        'tr': (params) => ({
            alpha: 0.1,
        }),
        'm': (params) => ({
            offsetY: -3,
        }),
    }
}
